import { Router } from 'express';
import { getUserDetails, login, updateUserName } from '../controllers/user';
import { authenticate, AuthenticatedRequest } from '../middlewares/authenticate';
import { cacheJsonMiddleware, IResponseCached } from '../middlewares/cacheJsonMiddleware';

const router = Router();

/**
 * @swagger
 * /user/login:
 *   post:
 *     summary: Authenticate user and generate JWT token
 *     description: |
 *       This endpoint authenticates users using their wallet signature and returns a JWT token.
 *       The token can be used to access protected routes in the application.
 *       Users can optionally provide a referrer code during login.
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - message
 *               - signature
 *               - chainType
 *               - walletAddress
 *             properties:
 *               message:
 *                 type: string
 *                 description: The message that was signed by the user's wallet
 *                 example: "Sign this message to authenticate with Launchpad"
 *               signature:
 *                 type: string
 *                 description: The signature of the message generated by the user's wallet
 *                 example: "0x1234..."
 *               referrerCode:
 *                 type: string
 *                 description: Optional referral code from another user
 *                 pattern: '^[A-Z0-9]{6,12}$'
 *                 example: "CRYPTO123"
 *               walletAddress:
 *                 $ref: '#/components/schemas/WalletAddress'
 *               chainType:
 *                 type: string
 *                 enum: [evm, svm]
 *                 description: The blockchain type (EVM for Ethereum Virtual Machine or SVM for Solana Virtual Machine)
 *                 example: "evm"
 *     responses:
 *       200:
 *         description: Login successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     userId:
 *                       type: string
 *                       format: uuid
 *                       example: "123e4567-e89b-12d3-a456-426614174000"
 *                     userName:
 *                       type: string
 *                       example: "crypto_trader123"
 *                     jwt:
 *                       type: string
 *                       example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
 *       400:
 *         description: Invalid request parameters
 *       401:
 *         description: Authentication failed
 */
router.post('/login', async (req, res) => {
  const { message, signature, chainType, walletAddress, referrerCode } = req.body;
  const data = await login(message, signature, chainType, walletAddress, referrerCode);
  res.json({ success: true, data });
});

/**
 * @swagger
 * /user/updateUserName:
 *   post:
 *     summary: Update the user's display name
 *     description: |
 *       This endpoint allows authenticated users to update their display name.
 *       The new name must be unique and meet certain validation criteria.
 *       Username must be between 3-30 characters and can only contain alphanumeric characters and underscores.
 *     tags: [User]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - userName
 *             properties:
 *               userName:
 *                 type: string
 *                 description: The new display name for the user
 *                 minLength: 3
 *                 maxLength: 30
 *                 pattern: '^[a-zA-Z0-9_]+$'
 *                 example: "crypto_trader123"
 *     responses:
 *       200:
 *         description: Username updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     userName:
 *                       type: string
 *                       example: "crypto_trader123"
 *       400:
 *         description: Invalid username or username already taken
 *       401:
 *         description: Unauthorized - Invalid or missing JWT token
 */
router.post('/updateUserName', authenticate, async (req: AuthenticatedRequest, res) => {
  const { userName } = req.body;
  const data = await updateUserName(req.user, userName);
  res.json({ success: true, data });
});

/**
 * @swagger
 * /user/details:
 *   get:
 *     summary: Retrieve user profile information
 *     description: |
 *       This endpoint returns detailed information about a user's profile,
 *       including their social media details, token holdings, and created tokens.
 *       The response is cached for 10 seconds to improve performance.
 *     tags: [User]
 *     parameters:
 *       - in: query
 *         name: walletAddress
 *         required: true
 *         schema:
 *           $ref: '#/components/schemas/WalletAddress'
 *         description: The wallet address of the user
 *       - in: query
 *         name: chainId
 *         required: true
 *         schema:
 *           $ref: '#/components/schemas/ChainId'
 *         description: The chain ID to fetch token data from
 *     responses:
 *       200:
 *         description: User details retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     userDetails:
 *                       type: object
 *                       properties:
 *                         userName:
 *                           type: string
 *                           example: "crypto_trader123"
 *                         walletAddress:
 *                           $ref: '#/components/schemas/WalletAddress'
 *                         twitterVerified:
 *                           type: boolean
 *                           example: true
 *                         twitchVerified:
 *                           type: boolean
 *                           example: false
 *                         twitterId:
 *                           type: string
 *                           example: "123456789"
 *                         twitterScreenName:
 *                           type: string
 *                           example: "crypto_trader"
 *                         twitterFollowers:
 *                           type: number
 *                           example: 1000
 *                         twitterAccountAgeInDay:
 *                           type: number
 *                           example: 365
 *                         totalTweets:
 *                           type: number
 *                           example: 500
 *                         twitterProfileImageUrl:
 *                           type: string
 *                           format: uri
 *                           example: "https://twitter.com/profile.jpg"
 *                     social:
 *                       type: object
 *                       properties:
 *                         followingCount:
 *                           type: number
 *                           example: 100
 *                         followersCount:
 *                           type: number
 *                           example: 200
 *                         messageCount:
 *                           type: number
 *                           example: 50
 *                     tokensCreated:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           basicDetails:
 *                             type: object
 *                             properties:
 *                               address:
 *                                 $ref: '#/components/schemas/WalletAddress'
 *                               name:
 *                                 type: string
 *                                 example: "MyToken"
 *                               symbol:
 *                                 type: string
 *                                 example: "MTK"
 *                     holdings:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           basicDetails:
 *                             type: object
 *                             properties:
 *                               address:
 *                                 $ref: '#/components/schemas/WalletAddress'
 *                               name:
 *                                 type: string
 *                                 example: "HeldToken"
 *                               symbol:
 *                                 type: string
 *                                 example: "HTK"
 *                           holdingPercent:
 *                             type: number
 *                             format: float
 *                             example: 5.5
 *                           amountHolding:
 *                             type: number
 *                             format: float
 *                             example: 1000.5
 *       400:
 *         description: Invalid request parameters
 *       404:
 *         description: User not found
 */
router.get('/details', cacheJsonMiddleware(10), async (req, res: IResponseCached) => {
  const { walletAddress, chainId } = req.query;
  const data = await getUserDetails({
    walletAddress: walletAddress as string,
    chainId: chainId as string,
  });
  res.jsonCached({ success: true, data });
});

export default router;
